services:
  - type: web
    name: caso-6-vulnerable
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vulnerable_app:app --bind 0.0.0.0:$PORT
    autoDeploy: true

  - type: web
    name: caso-6-secure
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn secure_app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
